# Generated by Django 5.1.3 on 2025-03-28 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_allocated_variant_inventoryreceipt_product'),
        ('products', '0001_initial'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batchitem',
            name='unique_batch_product',
        ),
        migrations.RemoveConstraint(
            model_name='batchitem',
            name='unique_batch_parent_product',
        ),
        migrations.RemoveConstraint(
            model_name='batchitem',
            name='batch_item_has_product_or_parent',
        ),
        migrations.RemoveConstraint(
            model_name='batchitem',
            name='batch_item_not_both_product_types',
        ),
        migrations.RenameField(
            model_name='batchitem',
            old_name='parent_product',
            new_name='product_family',
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='create_product_units',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Preferred product variant (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='requires_unit_qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='skip_inventory_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='batchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'product_family'), name='unique_batch_family'),
        ),
    ]
