# Generated by Django 5.1.3 on 2025-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_batchitem_source_id_batchitem_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='destination',
            field=models.CharField(choices=[('inventory', 'Direct to Inventory'), ('qc', 'Quality Control'), ('pending', 'Pending Decision')], default='pending', help_text='Where to send this item after receiving', max_length=20),
        ),
    ]
