# Generated by Django 5.1.3 on 2025-05-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0004_batchitem_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='destination',
        ),
    ]
