# Generated by Django 5.1.3 on 2025-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0005_remove_batchitem_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='skip_inventory_receipt',
            field=models.BooleanField(default=True),
        ),
    ]
