# Generated by Django 5.1.3 on 2025-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0006_alter_batchitem_skip_inventory_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='item_details',
            field=models.JSONField(blank=True, default=dict, help_text='Product specifications that vary by type - laptops: processor/RAM/storage, phones: storage/color, etc.'),
        ),
    ]
