# Generated by Django 5.1.3 on 2025-06-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0007_batchitem_item_details'),
    ]

    operations = [
    ]
