# Generated by Django 5.1.3 on 2025-06-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0008_auto_20250602_0503'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batchitem',
            name='unique_batch_family',
        ),
    ]
