# Generated by Django 5.1.3 on 2025-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestitem',
            name='is_family_mapped',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this item is mapped to a product family through its group'),
        ),
    ]
