# Generated by Django 5.1.3 on 2025-05-29 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_manifestitem_is_family_mapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestitem',
            name='is_family_mapped',
        ),
        migrations.AddField(
            model_name='manifestitem',
            name='family_mapped_group',
            field=models.ForeignKey(blank=True, help_text='Reference to group that provides family mapping for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_mapped_items', to='manifest.manifestgroup'),
        ),
    ]
