# Generated by Django 5.1.3 on 2025-03-27 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='allocated_variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant allocated for this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='receiving.receiptbatch'),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='product_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productfamily'),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='productunitreceipt',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productunit'),
        ),
        migrations.AddField(
            model_name='productunitreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_entries', to='inventory.inventoryreceipt'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('product_family__isnull', False)), name='receipt_has_product_family'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='productunitreceipt',
            unique_together={('receipt', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='stockalert',
            unique_together={('product', 'location')},
        ),
    ]
