# Generated by Django 5.1.3 on 2025-03-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreceipt',
            old_name='allocated_variant',
            new_name='product',
        ),
    ]
