# Generated by Django 5.1.3 on 2025-03-28 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_allocated_variant_inventoryreceipt_product'),
        ('products', '0002_product_metadata_alter_product_platform_and_more'),
        ('receiving', '0002_remove_batchitem_unique_batch_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryreceipt',
            name='receipt_has_product_family',
        ),
        migrations.AddConstraint(
            model_name='inventoryreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('product_family__isnull', False), ('product__isnull', False), _connector='OR'), name='receipt_has_product_or_family'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('product_family__isnull', True), ('product__isnull', True), _negated=True), name='receipt_must_have_product_reference'),
        ),
    ]
