# Generated by Django 5.1.3 on 2025-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventoryreceipt_receipt_has_product_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceipt',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Optional batch identifier', max_length=50, null=True),
        ),
    ]
