# Generated by Django 5.1.3 on 2025-04-26 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_metadata_alter_product_platform_and_more'),
        ('receiving', '0003_batchitem_source_id_batchitem_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='manifests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapping', 'Column Mapping'), ('validation', 'Validation'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_type', models.CharField(default='csv', max_length=20)),
                ('has_header', models.BooleanField(default=True)),
                ('row_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='PO number or reference', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('receipt_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_manifest', to='receiving.receiptbatch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manifest',
                'verbose_name_plural': 'Manifests',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(help_text='Hash of grouped fields', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_group', to='receiving.batchitem')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='manifest.manifest')),
                ('product_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productfamily')),
            ],
            options={
                'ordering': ['manifest', '-quantity'],
                'unique_together': {('manifest', 'group_key')},
            },
        ),
        migrations.CreateModel(
            name='ManifestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('default_values', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='manifest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests', to='manifest.manifesttemplate'),
        ),
        migrations.CreateModel(
            name='ManifestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Column Mapped'), ('validated', 'Validated'), ('error', 'Error'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('mapped_data', models.JSONField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('has_battery', models.BooleanField(default=False)),
                ('condition_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_items', to='receiving.batchitem')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='manifest.manifestgroup')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manifest.manifest')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('manifest', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ManifestColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(help_text='Column name in source file', max_length=100)),
                ('target_field', models.CharField(help_text='Field name in the system', max_length=100)),
                ('transform_function', models.CharField(blank=True, help_text='Optional function to transform the value', max_length=100, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('group_key', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='manifest.manifesttemplate')),
            ],
            options={
                'ordering': ['processing_order', 'source_column'],
                'unique_together': {('template', 'source_column')},
            },
        ),
    ]
