# Generated by Django 5.1.3 on 2025-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestitem',
            name='battery',
            field=models.CharField(blank=True, help_text='Battery status or condition', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manifests/'),
        ),
    ]
