# Generated by Django 5.1.3 on 2025-05-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_manifestitem_battery_alter_manifest_file'),
        ('receiving', '0003_batchitem_source_id_batchitem_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_manifests', to='receiving.receiptbatch'),
        ),
    ]
