# Generated by Django 5.1.3 on 2025-05-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_manifest_batch'),
        ('products', '0004_reconcile_migration_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestGroupFamilyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates if this is the primary family for this manifest group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('manifest_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_mappings', to='manifest.manifestgroup')),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_group_mappings', to='products.productfamily')),
            ],
            options={
                'verbose_name': 'Manifest Group Family Mapping',
                'verbose_name_plural': 'Manifest Group Family Mappings',
                'indexes': [models.Index(fields=['manifest_group', 'is_primary'], name='mg_family_primary_idx')],
                'unique_together': {('manifest_group', 'product_family')},
            },
        ),
    ]
