# Generated by Django 5.1.3 on 2025-05-21 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0004_manifestgroupfamilymapping'),
        ('products', '0004_reconcile_migration_history'),
        ('receiving', '0004_batchitem_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='batch',
        ),
        migrations.AddField(
            model_name='manifestgroup',
            name='additional_product_families',
            field=models.ManyToManyField(blank=True, help_text='Additional product families this group belongs to', related_name='additional_manifest_groups', to='products.productfamily'),
        ),
        migrations.AddField(
            model_name='manifestgroup',
            name='family_mapping_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='receipt_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests', to='receiving.receiptbatch'),
        ),
        migrations.AlterField(
            model_name='manifestgroup',
            name='product_family',
            field=models.ForeignKey(blank=True, help_text='The primary product family this group belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_manifest_groups', to='products.productfamily'),
        ),
        migrations.DeleteModel(
            name='ManifestGroupFamilyMapping',
        ),
    ]
