# Generated by Django 5.1.3 on 2025-05-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0005_remove_manifest_batch_and_more'),
        ('products', '0004_reconcile_migration_history'),
        ('receiving', '0004_batchitem_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestgroup',
            name='additional_product_families',
        ),
        migrations.AddField(
            model_name='manifestgroup',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata about the group such as line numbers, grouping criteria, variations of non-grouped fields', null=True),
        ),
        migrations.AlterField(
            model_name='manifestgroup',
            name='product_family',
            field=models.ForeignKey(blank=True, help_text='The product family this group belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_groups', to='products.productfamily'),
        ),
        migrations.AddIndex(
            model_name='manifestgroup',
            index=models.Index(fields=['manufacturer', 'model'], name='manifest_ma_manufac_c87d80_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestgroup',
            index=models.Index(fields=['processor'], name='manifest_ma_process_72da83_idx'),
        ),
    ]
