# Generated by Django 5.1.3 on 2025-03-27 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('warranty_period', models.PositiveIntegerField(default=3, help_text='Initial warranty period in months.')),
                ('extended_period', models.PositiveIntegerField(default=0, help_text='Additional warranty period in months.')),
                ('warranty_expiration_date', models.DateField(blank=True, null=True)),
                ('is_extended', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_registered', 'Not Registered'), ('active', 'Active'), ('expired', 'Expired'), ('void', 'Void')], default='not_registered', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('max_extensions', models.PositiveIntegerField(default=2, help_text='Maximum allowed extensions.')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='orders.order')),
                ('product_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productunit')),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('not_registered', 'Not Registered'), ('active', 'Active'), ('expired', 'Expired'), ('void', 'Void'), ('extended', 'Extended'), ('reset', 'Reset'), ('created', 'Created'), ('admin_edit', 'Admin Edit')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='warranties.warranty')),
            ],
            options={
                'verbose_name': 'Warranty Log',
                'verbose_name_plural': 'Warranty Logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
