# Generated by Django 4.2.2 on 2025-02-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='activation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='extended_period',
            field=models.PositiveIntegerField(default=0, help_text='Additional warranty period in months.'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_period',
            field=models.PositiveIntegerField(default=3, help_text='Initial warranty period in months.'),
        ),
    ]
