# Generated by Django 4.2.2 on 2025-02-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0002_warranty_activation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='activation_code',
        ),
    ]
