# Generated by Django 5.1.3 on 2025-03-27 22:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Internal unique order ID from platform.', max_length=100, unique=True)),
                ('customer_order_id', models.CharField(blank=True, help_text='Customer Order ID from the platform.', max_length=100, null=True)),
                ('platform', models.CharField(choices=[('walmart_ca', 'Walmart Canada'), ('walmart_us', 'Walmart US'), ('amazon', 'Amazon'), ('shopify', 'Shopify'), ('bestbuy', 'BestBuy'), ('manual', 'Manual Entry')], help_text='Platform where the order originated.', max_length=50)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total order amount, including taxes and discounts.', max_digits=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Date when the order was created.')),
                ('delivery_deadline', models.DateTimeField(blank=True, help_text='Deadline for order delivery.', null=True)),
                ('ship_date', models.DateTimeField(blank=True, help_text='Date the order was shipped.', null=True)),
                ('state', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='created', help_text='Current order status.', max_length=20)),
                ('platform_specific_data', models.JSONField(blank=True, default=dict, help_text='Platform-specific order details.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for the last update to the order.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of the product in this order item.')),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned'), ('shipped', 'Shipped'), ('returned', 'Returned')], default='pending', help_text='The current status of the order item.', max_length=20)),
                ('price_data', models.JSONField(blank=True, default=dict, help_text='JSON field storing pricing and tax details for the item.')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='The total price of the item, including taxes.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this item was last updated.')),
                ('order', models.ForeignKey(help_text='The parent order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
