# Generated by Django 4.2.2 on 2025-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_unit',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_units',
            field=models.ManyToManyField(blank=True, help_text='The specific product units assigned to this order item (for serialized products).', related_name='order_items', to='products.productunit'),
        ),
    ]
