# Generated by Django 4.2.2 on 2025-01-31 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_remove_orderitem_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_units',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_units',
            field=models.ForeignKey(blank=True, help_text='The specific product units assigned to this order item (for serialized products).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productunit'),
        ),
    ]
