# Generated by Django 4.2.2 on 2025-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productunit_order_item'),
        ('orders', '0003_remove_orderitem_product_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_units',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_units',
            field=models.ManyToManyField(blank=True, help_text='The specific product units assigned to this order item (for serialized products).', related_name='order_items', to='products.productunit'),
        ),
    ]
