# Generated by Django 4.2.2 on 2025-02-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_product_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_units',
        ),
    ]
