# Generated by Django 4.2.2 on 2025-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_product_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total order amount, including taxes and discounts.', max_digits=10, null=True),
        ),
    ]
