# Generated by Django 4.2.2 on 2025-01-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name or title', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True)),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=14, null=True, unique=True)),
                ('product_type', models.CharField(help_text='Product category or type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('platform', models.CharField(choices=[('walmart_ca', 'Walmart Canada'), ('walmart_us', 'Walmart US'), ('amazon', 'Amazon'), ('shopify', 'Shopify'), ('bestbuy', 'BestBuy'), ('manual', 'Manual Entry')], help_text='Platform where the product was first fetched or imported.', max_length=50)),
                ('platform_data', models.JSONField(default=dict, help_text='Platform-specific data for each platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('manufacturer_serial', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('assigned', 'Assigned to Order'), ('sold', 'Sold or Shipped'), ('returned', 'Returned'), ('defective', 'Defective')], default='in_stock', max_length=50)),
                ('is_serialized', models.BooleanField(default=True, help_text='Whether the product unit is serialized.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.product')),
            ],
        ),
    ]
