# Generated by Django 5.1.3 on 2025-03-27 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='Base SKU for this family', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('server', 'Server'), ('tablet', 'Tablet'), ('phone', 'Smartphone'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('networking', 'Networking Equipment'), ('accessory', 'Accessory'), ('peripheral', 'Peripheral'), ('component', 'Component'), ('storage', 'Storage Device'), ('software', 'Software'), ('other', 'Other')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Families',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name or title', max_length=255)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True)),
                ('gtin', models.CharField(blank=True, help_text='Global Trade Item Number', max_length=14, null=True, unique=True)),
                ('product_type', models.CharField(help_text='Product category or type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('platform', models.CharField(choices=[('walmart_ca', 'Walmart Canada'), ('walmart_us', 'Walmart US'), ('amazon', 'Amazon'), ('shopify', 'Shopify'), ('bestbuy', 'BestBuy'), ('manual', 'Manual Entry')], help_text='Platform where the product was first fetched or imported.', max_length=50)),
                ('price_data', models.JSONField(default=dict, help_text='Price data for each platform')),
                ('platform_data', models.JSONField(default=dict, help_text='Platform-specific data for each platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_primary_listing', models.BooleanField(default=False, help_text='Whether this is the primary listing for this product family')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productfamily')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('manufacturer_serial', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending_qc', 'Pending Quality Control'), ('in_stock', 'In Stock'), ('allocated', 'Allocated'), ('shipped', 'Shipped'), ('sold', 'Sold'), ('returned', 'Returned'), ('defective', 'Defective')], default='in_stock', max_length=20)),
                ('is_serialized', models.BooleanField(default=True, help_text='Whether the product unit is serialized.')),
                ('activation_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('batch_code', models.CharField(blank=True, help_text='Batch identifier for grouped units', max_length=20, null=True)),
                ('location_details', models.JSONField(blank=True, default=dict, help_text='Detailed location information (shelf, bin, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata about this unit (receipt info, seller, etc)', null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_units', to='inventory.location')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units_relation', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnitAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('reassigned', 'Reassigned')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='orders.orderitem')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='products.productunit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnitLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_details', models.JSONField(blank=True, default=dict)),
                ('new_details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location')),
                ('previous_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='products.productunit')),
            ],
        ),
    ]
