# Generated by Django 5.1.3 on 2025-03-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about this product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('walmart_ca', 'Walmart Canada'), ('walmart_us', 'Walmart US'), ('amazon', 'Amazon'), ('shopify', 'Shopify'), ('bestbuy', 'BestBuy'), ('manual', 'Manual Entry')], default='manual', help_text='Platform where the product was first fetched or imported.', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform_data',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific data for each platform'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_data',
            field=models.JSONField(blank=True, default=dict, help_text='Price data for each platform'),
        ),
    ]
