# Generated by Django 5.1.3 on 2025-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_metadata_alter_product_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfamily',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Product family attributes like processor, screen size, etc.'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords for search optimization, comma-separated', null=True),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['manufacturer', 'model'], name='products_pr_manufac_1bddaf_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['product_type'], name='products_pr_product_36d8e0_idx'),
        ),
    ]
