# Generated by Django 4.2.2 on 2025-01-31 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productunit_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='order_item',
        ),
    ]
