# Generated by Django 5.1.3 on 2025-05-12 20:15

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a reconciliation migration that handles all intermediate migrations
    that may have been applied to the database but whose files are missing.
    
    It resolves the dependency chain from migration 0003 to the latest state
    without requiring any actual database changes.
    """
    replaces = [
        ('products', '0004_productunit_order_item_productunitassignmenthistory'),
        ('products', '0005_productunit_activation_code'),
        ('products', '0006_alter_productunit_activation_code'),
        ('products', '0007_product_regular_price_product_sale_price'),
        ('products', '0008_product_price_data'),
        ('products', '0009_productunit_batch_code_productunit_metadata'),
        ('products', '0009_auto_20240501_0000'),
        ('products', '0010_alter_productunit_status'),
        ('products', '0010_productfamily_enhancements'),
        ('products', '0011_productunit_location_productunit_location_details_and_more'),
        ('products', '0012_productfamily_product_family'),
        ('products', '0013_product_is_primary_listing'),
    ]

    dependencies = [
        ('products', '0003_productfamily_attributes_productfamily_category_and_more'),
    ]

    operations = [
        # No operations needed, this is a reconciliation migration
    ]
