# Generated by Django 4.2.2 on 2025-02-01 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_product_units'),
        ('products', '0003_remove_productunit_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units_relation', to='orders.orderitem'),
        ),
        migrations.CreateModel(
            name='ProductUnitAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('reassigned', 'Reassigned')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_history', to='orders.orderitem')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='products.productunit')),
            ],
        ),
    ]
