# Generated by Django 4.2.2 on 2025-02-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productunit_order_item_productunitassignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='activation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
