# Generated by Django 5.1.3 on 2025-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reconcile_migration_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='batch_code',
            field=models.CharField(blank=True, help_text='Batch identifier for grouped units', max_length=50, null=True),
        ),
    ]
